import React, { useState } from 'react';
import { 
  Sparkles, 
  ArrowRight, 
  ShieldCheck, 
  Cpu, 
  Database, 
  FileText, 
  Search, 
  CheckCircle2, 
  Terminal, 
  Copy, 
  Check, 
  Layers, 
  FileCode, 
  Zap, 
  HelpCircle,
  ExternalLink,
  ChevronDown,
  Lock,
  Boxes,
  FileSpreadsheet
} from 'lucide-react';

export default function LandingPage({ onGetStarted, health }) {
  const [copied, setCopied] = useState(false);
  const [activeStep, setActiveStep] = useState(1);
  const [openFaq, setOpenFaq] = useState(null);

  const copyCommand = () => {
    navigator.clipboard.writeText('ollama run llama3.2:1b');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const steps = [
    {
      num: 1,
      title: "Document Ingestion",
      desc: "Upload multi-page PDFs or PPTX slide decks. PyMuPDF and python-pptx parse structural text and metadata.",
      tag: "PyMuPDF / PPTX"
    },
    {
      num: 2,
      title: "Smart Chunking",
      desc: "Documents are split into 500-character semantically coherent chunks with 100-character sliding overlap.",
      tag: "Recursive Splitter"
    },
    {
      num: 3,
      title: "Dense Vector Embedding",
      desc: "Each chunk is transformed into a 384-dimensional dense vector using the local all-MiniLM-L6-v2 model.",
      tag: "SentenceTransformers"
    },
    {
      num: 4,
      title: "FAISS Vector Index",
      desc: "Vectors are indexed in a high-speed FAISS FlatIP index for sub-millisecond inner product cosine search.",
      tag: "FAISS Engine"
    },
    {
      num: 5,
      title: "Grounded LLM Synthesis",
      desc: "Top relevant chunks are assembled into a context prompt and synthesized by LLaMA 3.2 / Gemma with citations.",
      tag: "Ollama Local LLM"
    }
  ];

  const faqs = [
    {
      q: "Does any document data leave my computer?",
      a: "No. Everything runs 100% locally. The document parser, embedding engine (MiniLM-L6-v2), vector database (FAISS), and LLM (Ollama) execute strictly on your local machine with zero external network calls."
    },
    {
      q: "What file formats are currently supported?",
      a: "The system natively parses PDF documents (.pdf) and Microsoft PowerPoint presentations (.pptx, .ppt), including slide titles, bullet points, and speaker notes."
    },
    {
      q: "Which local language models can I use?",
      a: "You can use any model available in Ollama, including LLaMA 3.2 (1B/3B), Gemma (2B/7B), Qwen 2.5 (1.5B), Mistral (7B), and Phi-3. Simply set your preferred model in the backend config."
    },
    {
      q: "How does source attribution and citation work?",
      a: "Every response generated by the assistant includes verified source cards showing the exact file name, slide/page number, similarity score, and excerpt from the original document."
    }
  ];

  return (
    <div className="hf-landing">
      {/* 1. Announcement / Advertisement Banner */}
      <div className="hf-announcement-bar">
        <div className="hf-announcement-content">
          <span className="hf-announcement-badge">SPONSORED UPDATE</span>
          <span className="hf-announcement-text">
            🚀 <strong>DocuMind v2.4 Release:</strong> Multi-format presentation parsing & instant semantic grounding with zero API fees.
          </span>
          <button className="hf-announcement-link" onClick={onGetStarted}>
            Launch Workspace <ArrowRight size={13} />
          </button>
        </div>
      </div>

      {/* 2. Hero Section */}
      <section className="hf-hero">
        <div className="hf-hero-badge">
          <ShieldCheck size={14} className="text-emerald" />
          <span>100% On-Device Privacy • No Cloud Dependencies</span>
        </div>

        <h1 className="hf-hero-title">
          Private Document Intelligence <br />
          <span className="hf-gradient-text">Powered by Local AI & Vector Search</span>
        </h1>

        <p className="hf-hero-subtitle">
          Ingest PDFs, technical briefs, and PowerPoint slide decks into an offline, verifiable RAG pipeline. 
          Extract instant factual answers with strict source page citations using dense semantic embeddings and local LLMs.
        </p>

        {/* Hero Actions */}
        <div className="hf-hero-actions">
          <button className="hf-btn-hero-primary" onClick={onGetStarted}>
            <span>Get Started with Your Documents</span>
            <ArrowRight size={18} />
          </button>

          <a href="#pipeline" className="hf-btn-hero-secondary">
            <Cpu size={17} />
            <span>Explore Architecture</span>
          </a>
        </div>

        {/* Quick CLI Chip */}
        <div className="hf-cli-chip" onClick={copyCommand}>
          <Terminal size={14} className="hf-cli-icon" />
          <span className="hf-cli-label">Quick Start:</span>
          <code className="hf-cli-code">ollama run llama3.2:1b</code>
          <span className="hf-cli-copy">
            {copied ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
          </span>
        </div>
      </section>

      {/* 3. Product Mockup / Interactive Preview */}
      <section className="hf-preview-section">
        <div className="hf-preview-window">
          <div className="hf-window-header">
            <div className="hf-window-dots">
              <span className="dot red"></span>
              <span className="dot yellow"></span>
              <span className="dot green"></span>
            </div>
            <div className="hf-window-title">DocuMind Local RAG — Grounded Document Assistant</div>
            <div className="hf-window-tag">FAISS FlatIP • MiniLM-L6-v2 • Local LLM</div>
          </div>

          <div className="hf-window-body">
            {/* Left Mockup: Ingested Document */}
            <div className="hf-mockup-pane">
              <div className="hf-pane-title">
                <FileText size={15} color="#e3b341" />
                <span>Indexed Document Context</span>
              </div>
              <div className="hf-doc-item active">
                <div className="hf-doc-header">
                  <span className="hf-doc-icon">📊</span>
                  <div>
                    <div className="hf-doc-name">Tactical_Micro_Recon_Drone.pptx</div>
                    <div className="hf-doc-meta">16 Slides • 50 Chunks • 384-D Embeddings</div>
                  </div>
                </div>
                <div className="hf-doc-snippet">
                  <strong>Slide 1:</strong> Tactical Micro-Recon Drone for Real-Time Battlefield Situational Awareness. Team: Ahilesh, Aswanth, Hari Haran, Subin Raj. Guide: Mrs. Savitha S.
                </div>
              </div>

              <div className="hf-chunk-pills">
                <span className="hf-chip">✓ Slide 1 (Team & Scope)</span>
                <span className="hf-chip">✓ Slide 4 (Month 1 Work)</span>
                <span className="hf-chip">✓ Slide 12 (Roadmap)</span>
                <span className="hf-chip">✓ Slide 16 (Summary)</span>
              </div>
            </div>

            {/* Right Mockup: Grounded Chat Output */}
            <div className="hf-mockup-pane right">
              <div className="hf-pane-title">
                <Sparkles size={15} color="#58a6ff" />
                <span>Grounded Verification Response</span>
              </div>

              <div className="hf-mock-query">
                <strong>User Inquiry:</strong> Who are the team members and what is the project about?
              </div>

              <div className="hf-mock-answer">
                <div className="hf-answer-heading"><strong>Project Team & Overview:</strong></div>
                <ul>
                  <li><strong>Team Members:</strong> Ahilesh, Aswanth, Hari Haran, Subin Raj</li>
                  <li><strong>Faculty Guide:</strong> Mrs. Savitha S (Department of CSE)</li>
                  <li><strong>Project Purpose:</strong> Sub-250g Tactical Micro-Recon Drone for real-time battlefield situational awareness with edge AI detection.</li>
                </ul>

                <div className="hf-mock-sources">
                  <div className="hf-sources-label">Verified Citations:</div>
                  <div className="hf-source-tag">
                    <span>📄 Slide 1 (Title & Team)</span>
                    <span className="hf-score">95% Match</span>
                  </div>
                  <div className="hf-source-tag">
                    <span>📄 Slide 3 (Objectives)</span>
                    <span className="hf-score">89% Match</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 4. Trust & Metrics Bar */}
      <section className="hf-metrics-bar">
        <div className="hf-metric-item">
          <div className="hf-metric-val">&lt; 3 ms</div>
          <div className="hf-metric-label">Vector Search Latency</div>
        </div>
        <div className="hf-metric-divider"></div>
        <div className="hf-metric-item">
          <div className="hf-metric-val">100%</div>
          <div className="hf-metric-label">Air-Gapped Privacy</div>
        </div>
        <div className="hf-metric-divider"></div>
        <div className="hf-metric-item">
          <div className="hf-metric-val">384-D</div>
          <div className="hf-metric-label">Dense Vector Embeddings</div>
        </div>
        <div className="hf-metric-divider"></div>
        <div className="hf-metric-item">
          <div className="hf-metric-val">$0.00</div>
          <div className="hf-metric-label">Cloud API Cost</div>
        </div>
      </section>

      {/* 5. Core Feature Grid */}
      <section className="hf-features-section" id="features">
        <div className="hf-section-header">
          <span className="hf-section-tag">ENGINEERED FOR PRIVACY & PRECISION</span>
          <h2 className="hf-section-title">Why Local Document Intelligence?</h2>
          <p className="hf-section-desc">
            Designed for research labs, technical teams, and organizations that demand high-accuracy search without compromising sensitive documents.
          </p>
        </div>

        <div className="hf-feature-grid">
          <div className="hf-feature-card">
            <div className="hf-card-icon-wrap amber">
              <Lock size={20} />
            </div>
            <h3 className="hf-card-title">Air-Gapped Data Privacy</h3>
            <p className="hf-card-desc">
              Zero cloud transmission. Documents, embeddings, vectors, and chat prompts never leave your local machine or internal network.
            </p>
            <div className="hf-card-footer-pill">100% On-Premise</div>
          </div>

          <div className="hf-feature-card">
            <div className="hf-card-icon-wrap blue">
              <Database size={20} />
            </div>
            <h3 className="hf-card-title">FAISS Vector Search Engine</h3>
            <p className="hf-card-desc">
              Leverages Meta's FAISS library with Inner Product cosine similarity to rank chunks in sub-millisecond speeds with strict thresholds.
            </p>
            <div className="hf-card-footer-pill">FlatIP Cosine Index</div>
          </div>

          <div className="hf-feature-card">
            <div className="hf-card-icon-wrap purple">
              <FileSpreadsheet size={20} />
            </div>
            <h3 className="hf-card-title">Multi-Format Extraction</h3>
            <p className="hf-card-desc">
              Deep parsing for PowerPoint decks (.pptx) and PDFs (.pdf). Extracts slide tables, bullet hierarchies, and speaker notes accurately.
            </p>
            <div className="hf-card-footer-pill">PDF & PPTX Native</div>
          </div>

          <div className="hf-feature-card">
            <div className="hf-card-icon-wrap emerald">
              <CheckCircle2 size={20} />
            </div>
            <h3 className="hf-card-title">Grounded Source Citations</h3>
            <p className="hf-card-desc">
              Every answer provides verifiable citations highlighting the exact page, similarity percentage, and textual excerpt to eliminate hallucinations.
            </p>
            <div className="hf-card-footer-pill">Verifiable Evidence</div>
          </div>
        </div>
      </section>

      {/* 6. Architecture Dataflow Pipeline */}
      <section className="hf-pipeline-section" id="pipeline">
        <div className="hf-section-header">
          <span className="hf-section-tag">UNDER THE HOOD</span>
          <h2 className="hf-section-title">5-Stage RAG Pipeline Architecture</h2>
          <p className="hf-section-desc">
            A look into how documents transform from raw files into structured semantic intelligence.
          </p>
        </div>

        <div className="hf-pipeline-container">
          <div className="hf-pipeline-tabs">
            {steps.map((step) => (
              <button
                key={step.num}
                className={`hf-pipeline-tab ${activeStep === step.num ? 'active' : ''}`}
                onClick={() => setActiveStep(step.num)}
              >
                <span className="hf-step-num">{step.num}</span>
                <div className="hf-step-meta">
                  <div className="hf-step-title">{step.title}</div>
                  <div className="hf-step-tag">{step.tag}</div>
                </div>
              </button>
            ))}
          </div>

          <div className="hf-pipeline-detail">
            <div className="hf-pipeline-detail-header">
              <span className="hf-detail-badge">STAGE {steps[activeStep - 1].num} OF 5</span>
              <h3 className="hf-detail-title">{steps[activeStep - 1].title}</h3>
            </div>
            <p className="hf-detail-desc">{steps[activeStep - 1].desc}</p>
            <div className="hf-detail-tech">
              <div className="hf-tech-item">
                <span className="label">Component:</span>
                <span className="val">{steps[activeStep - 1].tag}</span>
              </div>
              <div className="hf-tech-item">
                <span className="label">Execution:</span>
                <span className="val">Local Subsystem</span>
              </div>
              <div className="hf-tech-item">
                <span className="label">Latency:</span>
                <span className="val">&lt; 10ms</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 7. Advertisement / Enterprise Callout Banner */}
      <section className="hf-sponsor-banner">
        <div className="hf-sponsor-inner">
          <div className="hf-sponsor-badge">FEATURED CAPABILITY</div>
          <h3 className="hf-sponsor-title">Built for Confidential Research, Engineering & Defense</h3>
          <p className="hf-sponsor-desc">
            Proprietary research, patents, defense specifications, and internal corporate slides require zero-trust environments. 
            DocuMind provides complete data isolation with top-tier AI retrieval.
          </p>
          <div className="hf-sponsor-actions">
            <button className="hf-btn-hero-primary" onClick={onGetStarted}>
              <span>Launch Document Assistant</span>
              <ArrowRight size={16} />
            </button>
          </div>
        </div>
      </section>

      {/* 8. FAQ Section */}
      <section className="hf-faq-section">
        <div className="hf-section-header">
          <span className="hf-section-tag">FREQUENTLY ASKED QUESTIONS</span>
          <h2 className="hf-section-title">Technical Specifications & FAQ</h2>
        </div>

        <div className="hf-faq-list">
          {faqs.map((faq, idx) => (
            <div key={idx} className={`hf-faq-item ${openFaq === idx ? 'open' : ''}`}>
              <button className="hf-faq-question" onClick={() => toggleFaq(idx)}>
                <span>{faq.q}</span>
                <ChevronDown size={18} className="hf-faq-arrow" />
              </button>
              {openFaq === idx && (
                <div className="hf-faq-answer">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* 9. Clean Developer Footer */}
      <footer className="hf-footer">
        <div className="hf-footer-inner">
          <div className="hf-footer-brand">
            <div className="hf-brand-title">DocuMind Local RAG</div>
            <p className="hf-footer-desc">
              Open-architecture local retrieval-augmented generation pipeline powered by FAISS, SentenceTransformers, and Ollama.
            </p>
          </div>

          <div className="hf-footer-links">
            <div className="hf-footer-col">
              <h4>System</h4>
              <button onClick={onGetStarted}>Workspace</button>
              <a href="#pipeline">Architecture</a>
              <a href="#features">Features</a>
            </div>
            <div className="hf-footer-col">
              <h4>Stack</h4>
              <span>FAISS (FlatIP)</span>
              <span>MiniLM-L6-v2</span>
              <span>Ollama (LLaMA 3.2 / Gemma)</span>
            </div>
          </div>
        </div>

        <div className="hf-footer-bottom">
          <span>© 2026 DocuMind Document Intelligence. Built for high-security local environments.</span>
          <span className="hf-status-indicator">
            <span className="dot online"></span> System Ready
          </span>
        </div>
      </footer>
    </div>
  );
}
